/* Linguagem20252.java */
/* Generated By:JavaCC: Do not edit this line. Linguagem20252.java */
import java.util.*;
import java.io.*;
import org.example.Semantico;

public class Linguagem20252 implements Linguagem20252Constants {

    public static final List<String> parseErrors = new ArrayList<>();
    public static final List<String> lexicalErrors = new ArrayList<>();

    public static void clearParseErrors() {
        parseErrors.clear();
        lexicalErrors.clear();
    }

    public static void printParseErrors() {
        for (String msg : parseErrors) {
            System.out.println(msg);
        }
    }

    void reportParseError(ParseException e) {
            Token tok = e.currentToken.next;
            String found = (tok == null) ? "EOF" : tok.image;
            int line = (tok == null) ? -1 : tok.beginLine;
            int col  = (tok == null) ? -1 : tok.beginColumn;

            StringBuilder expected = new StringBuilder();
            if (e.expectedTokenSequences != null) {
                for (int i = 0; i < e.expectedTokenSequences.length; i++) {
                    int[] seq = e.expectedTokenSequences[i];
                    if (i > 0) expected.append(" | ");
                    for (int j = 0; j < seq.length; j++) {
                        expected.append(Linguagem20252Constants.tokenImage[seq[j]]).append(" ");
                    }
                }
            } else {
                expected.append("token v\u00e1lido");
            }

            String msg = "Erro sint\u00e1tico na linha " + line + ", coluna " + col +
                         ": encontrado '" + found + "'. Esperado: " + expected.toString();
            Linguagem20252.parseErrors.add(msg);
            System.err.println(msg);
        }

    public static void main(String[] args) {
        try {
            clearParseErrors();
            Linguagem20252 parser = new Linguagem20252(System.in);
            parser.programa();

            if (!lexicalErrors.isEmpty()) {
                System.out.println("Foram encontrados erros l\u00e9xicos:");
                for (String msg : lexicalErrors) System.out.println("  - " + msg);
            } else if (!parseErrors.isEmpty()) {
                System.out.println("Foram encontrados erros sint\u00e1ticos:");
                printParseErrors();
            } else {
                System.out.println("Programa compilado com sucesso.");
            }

        } catch (ParseException e) {
            System.err.println("Erro sint\u00e1tico: " + e.getMessage());
        } catch (TokenMgrError tme) {
            System.err.println("Erro l\u00e9xico fatal: " + tme.getMessage());
        } catch (Exception ex) {
            System.err.println("Erro inesperado: " + ex.getMessage());
            ex.printStackTrace(System.err);
        }
    }

// Sintatico e lexico
  final public void programa() throws ParseException {
    try {
      jj_consume_token(BEGIN);
      identificador_programa();
      declaracao();
      jj_consume_token(START);
      lista_de_comandos();
Semantico.P2();
      jj_consume_token(END);
      jj_consume_token(PONTO);
      jj_consume_token(0);
    } catch (ParseException e) {
reportParseError(e);
    skipUntil(new int[] {
        Linguagem20252Constants.END,
        Linguagem20252Constants.PONTO
    });
    }
}

  final public void identificador_programa() throws ParseException {Token id;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case IDENTIFICADOR:{
      id = jj_consume_token(IDENTIFICADOR);
Semantico.P1(id.image);
      break;
      }
    default:
      jj_la1[0] = jj_gen;
      ;
    }
}

  final public void declaracao() throws ParseException {
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case DEFINE:{
        jj_consume_token(DEFINE);
Semantico.D0();
        lista_de_declaracao();
        break;
        }
      default:
        jj_la1[1] = jj_gen;
        ;
      }
    } catch (ParseException e) {
reportParseError(e);
    skipUntil(new int[] {
        Linguagem20252Constants.START,
        Linguagem20252Constants.END
    });
    }
}

  final public void lista_de_declaracao() throws ParseException {
    declaracao_variaveis();
    lista_de_declaracao_prim();
}

  final public void lista_de_declaracao_prim() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case IDENTIFICADOR:{
      declaracao_variaveis();
      lista_de_declaracao_prim();
      break;
      }
    default:
      jj_la1[2] = jj_gen;
      ;
    }
}

  final public void declaracao_variaveis() throws ParseException {
    lista_de_identificadores();
    jj_consume_token(DOIS_PONTOS);
    tipo();
    decl_do_vetor();
    jj_consume_token(PONTO_E_VIRGULA);
Semantico.D6();
}

  final public void lista_de_identificadores() throws ParseException {Token id;
    id = jj_consume_token(IDENTIFICADOR);
Semantico.D1(id.image);
    lista_de_identificadores_prim();
}

  final public void lista_de_identificadores_prim() throws ParseException {Token id;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case VIRGULA:{
      jj_consume_token(VIRGULA);
      id = jj_consume_token(IDENTIFICADOR);
Semantico.D1(id.image);
      lista_de_identificadores_prim();
      break;
      }
    default:
      jj_la1[3] = jj_gen;
      ;
    }
}

  final public void tipo() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case NUM:{
      jj_consume_token(NUM);
Semantico.T(1);
      break;
      }
    case REAL:{
      jj_consume_token(REAL);
Semantico.T(2);
      break;
      }
    case TEXT:{
      jj_consume_token(TEXT);
Semantico.T(3);
      break;
      }
    case FLAG:{
      jj_consume_token(FLAG);
Semantico.T(4);
      break;
      }
    default:
      jj_la1[4] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  final public void decl_do_vetor() throws ParseException {Token c;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ABRE_COLCHETES:{
      jj_consume_token(ABRE_COLCHETES);
      c = jj_consume_token(CONSTANTE_INTEIRA);
Semantico.V1(Integer.parseInt(c.image));
      jj_consume_token(FECHA_COLCHETES);
      inic_vetor();
Semantico.V2();
      break;
      }
    default:
      jj_la1[5] = jj_gen;
      inic_escalar();
Semantico.E2(); Semantico.IE();
    }
}

  final public void inic_vetor() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ATRIBUICAO:{
      jj_consume_token(ATRIBUICAO);
      jj_consume_token(ABRE_CHAVES);
      lista_valores_vetor();
      jj_consume_token(FECHA_CHAVES);
Semantico.IV_End();
      break;
      }
    default:
      jj_la1[6] = jj_gen;
      ;
    }
}

  final public void inic_escalar() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ATRIBUICAO:{
      jj_consume_token(ATRIBUICAO);
      valor();
      break;
      }
    default:
      jj_la1[7] = jj_gen;
      ;
    }
}

  final public void lista_valores_vetor() throws ParseException {
    valor();
Semantico.VAL();
    lista_valores_vetor_prim();
}

  final public void lista_valores_vetor_prim() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case VIRGULA:{
      jj_consume_token(VIRGULA);
      valor();
Semantico.VAL();
      lista_valores_vetor_prim();
      break;
      }
    default:
      jj_la1[8] = jj_gen;
      ;
    }
}

  final public void valor() throws ParseException {Token t;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case CONSTANTE_INTEIRA:{
      t = jj_consume_token(CONSTANTE_INTEIRA);
Semantico.C1(Integer.parseInt(t.image));
      break;
      }
    case CONSTANTE_REAL:{
      t = jj_consume_token(CONSTANTE_REAL);
Semantico.C2(Double.parseDouble(t.image));
      break;
      }
    case CONSTANTE_LITERAL:{
      t = jj_consume_token(CONSTANTE_LITERAL);
Semantico.C3(t.image);
      break;
      }
    case TRUE:{
      jj_consume_token(TRUE);
Semantico.C4();
      break;
      }
    case FALSE:{
      jj_consume_token(FALSE);
Semantico.C5();
      break;
      }
    default:
      jj_la1[9] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  final public void lista_de_comandos() throws ParseException {
    try {
      comando();
      lista_de_comandos_prim();
    } catch (ParseException e) {
reportParseError(e);
    skipUntil(new int[] {
        Linguagem20252Constants.END,
        Linguagem20252Constants.ELSE,
        Linguagem20252Constants.PONTO_E_VIRGULA
    });
    }
}

  final public void lista_de_comandos_prim() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case SET:
    case READ:
    case SHOW:
    case IF:
    case LOOP:{
      comando();
      lista_de_comandos_prim();
      break;
      }
    default:
      jj_la1[10] = jj_gen;
      ;
    }
}

  final public void comando() throws ParseException {
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case SET:{
        atribuicao();
        break;
        }
      case READ:{
        entrada();
        break;
        }
      case SHOW:{
        saida();
        break;
        }
      case IF:{
        selecao();
        break;
        }
      case LOOP:{
        repeticao();
        break;
        }
      default:
        jj_la1[11] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (ParseException e) {
reportParseError(e);
    skipUntil(new int[] {
        Linguagem20252Constants.PONTO_E_VIRGULA,
        Linguagem20252Constants.END,
        Linguagem20252Constants.ELSE
    });
    }
}

  final public void atribuicao() throws ParseException {Token id;
    try {
      jj_consume_token(SET);
      id = jj_consume_token(IDENTIFICADOR);
Semantico.A1(id.image);
      indice();
Semantico.A2();
      jj_consume_token(ATRIBUICAO);
      expressao();
Semantico.A3();
      jj_consume_token(PONTO_E_VIRGULA);
    } catch (ParseException e) {
reportParseError(e);
    skipUntil(new int[] {
        Linguagem20252Constants.PONTO_E_VIRGULA
    });
    }
}

  final public void indice() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ABRE_COLCHETES:{
      jj_consume_token(ABRE_COLCHETES);
      expressao();
Semantico.I1();
      jj_consume_token(FECHA_COLCHETES);
      break;
      }
    default:
      jj_la1[12] = jj_gen;
      ;
    }
}

  final public void entrada() throws ParseException {Token id;
    jj_consume_token(READ);
    jj_consume_token(ABRE_PARENTESES);
    id = jj_consume_token(IDENTIFICADOR);
Semantico.R1(id.image);
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ABRE_COLCHETES:{
      jj_consume_token(ABRE_COLCHETES);
      expressao();
Semantico.R2();
      jj_consume_token(FECHA_COLCHETES);
      break;
      }
    default:
      jj_la1[13] = jj_gen;
      ;
    }
    jj_consume_token(FECHA_PARENTESES);
    jj_consume_token(PONTO_E_VIRGULA);
Semantico.R_Generate();
}

  final public void saida() throws ParseException {
    jj_consume_token(SHOW);
    jj_consume_token(ABRE_PARENTESES);
    lista_de_saida();
    jj_consume_token(FECHA_PARENTESES);
    jj_consume_token(PONTO_E_VIRGULA);
}

  final public void lista_de_saida() throws ParseException {
    item();
    lista_de_saida_prim();
}

  final public void lista_de_saida_prim() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case VIRGULA:{
      jj_consume_token(VIRGULA);
      item();
      lista_de_saida_prim();
      break;
      }
    default:
      jj_la1[14] = jj_gen;
      ;
    }
}

  final public void item() throws ParseException {Token id; Token t;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case IDENTIFICADOR:{
      id = jj_consume_token(IDENTIFICADOR);
Semantico.S2(id.image);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case ABRE_COLCHETES:{
        jj_consume_token(ABRE_COLCHETES);
        expressao();
Semantico.S3();
        jj_consume_token(FECHA_COLCHETES);
        break;
        }
      default:
        jj_la1[15] = jj_gen;
        ;
      }
Semantico.S_Generate();
      break;
      }
    case CONSTANTE_INTEIRA:{
      t = jj_consume_token(CONSTANTE_INTEIRA);
Semantico.K1(Integer.parseInt(t.image));
      break;
      }
    case CONSTANTE_REAL:{
      t = jj_consume_token(CONSTANTE_REAL);
Semantico.K2(Double.parseDouble(t.image));
      break;
      }
    case CONSTANTE_LITERAL:{
      t = jj_consume_token(CONSTANTE_LITERAL);
Semantico.K3(t.image);
      break;
      }
    default:
      jj_la1[16] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

  final public void selecao() throws ParseException {
    jj_consume_token(IF);
    expressao();
Semantico.F1();
    jj_consume_token(THEN);
    lista_de_comandos();
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ELSE:{
      jj_consume_token(ELSE);
Semantico.F2();
      lista_de_comandos();
      break;
      }
    default:
      jj_la1[17] = jj_gen;
      ;
    }
    jj_consume_token(END);
    jj_consume_token(PONTO_E_VIRGULA);
Semantico.F3();
}

  final public void repeticao() throws ParseException {
    jj_consume_token(LOOP);
    jj_consume_token(WHILE);
    expressao();
Semantico.L1();
    lista_de_comandos();
Semantico.L2();
    jj_consume_token(END);
    jj_consume_token(PONTO_E_VIRGULA);
}

  final public void expressao() throws ParseException {
    expressao_arit_logica();
    expressao_relacional();
}

  final public void expressao_relacional() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case IGUAL:
    case DIFERENTE:
    case MENOR_OU_IGUAL:
    case MAIOR_OU_IGUAL:
    case MENOR:
    case MAIOR:{
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IGUAL:{
        jj_consume_token(IGUAL);
        expressao_arit_logica();
Semantico.REQ();
        break;
        }
      case DIFERENTE:{
        jj_consume_token(DIFERENTE);
        expressao_arit_logica();
Semantico.RNEQ();
        break;
        }
      case MENOR:{
        jj_consume_token(MENOR);
        expressao_arit_logica();
Semantico.RLT();
        break;
        }
      case MAIOR:{
        jj_consume_token(MAIOR);
        expressao_arit_logica();
Semantico.RGT();
        break;
        }
      case MENOR_OU_IGUAL:{
        jj_consume_token(MENOR_OU_IGUAL);
        expressao_arit_logica();
Semantico.RLE();
        break;
        }
      case MAIOR_OU_IGUAL:{
        jj_consume_token(MAIOR_OU_IGUAL);
        expressao_arit_logica();
Semantico.RGE();
        break;
        }
      default:
        jj_la1[18] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
      }
    default:
      jj_la1[19] = jj_gen;
      ;
    }
}

  final public void expressao_arit_logica() throws ParseException {
    termo2();
    menor_prioridade();
}

  final public void menor_prioridade() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case MAIS:
    case MENOS:
    case OU:{
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case MAIS:{
        jj_consume_token(MAIS);
        termo2();
Semantico.ADD();
        menor_prioridade();
        break;
        }
      case MENOS:{
        jj_consume_token(MENOS);
        termo2();
Semantico.SUB();
        menor_prioridade();
        break;
        }
      case OU:{
        jj_consume_token(OU);
        termo2();
Semantico.OR();
        menor_prioridade();
        break;
        }
      default:
        jj_la1[20] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
      }
    default:
      jj_la1[21] = jj_gen;
      ;
    }
}

  final public void termo2() throws ParseException {
    termo1();
    media_prioridade();
}

  final public void media_prioridade() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case VEZES:
    case DIVIDIR:
    case DIVISAO_INTEIRA:
    case RESTO_DIVISAO:
    case E:{
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case VEZES:{
        jj_consume_token(VEZES);
        termo1();
Semantico.MUL();
        media_prioridade();
        break;
        }
      case DIVIDIR:{
        jj_consume_token(DIVIDIR);
        termo1();
Semantico.DIV();
        media_prioridade();
        break;
        }
      case DIVISAO_INTEIRA:{
        jj_consume_token(DIVISAO_INTEIRA);
        termo1();
Semantico.MOD();
        media_prioridade();
        break;
        }
      case RESTO_DIVISAO:{
        jj_consume_token(RESTO_DIVISAO);
        termo1();
Semantico.REM();
        media_prioridade();
        break;
        }
      case E:{
        jj_consume_token(E);
        termo1();
Semantico.AND();
        media_prioridade();
        break;
        }
      default:
        jj_la1[22] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
      }
    default:
      jj_la1[23] = jj_gen;
      ;
    }
}

  final public void termo1() throws ParseException {
    elemento();
    maior_prioridade();
}

  final public void maior_prioridade() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case POTENCIA:{
      jj_consume_token(POTENCIA);
      elemento();
Semantico.POW();
      maior_prioridade();
      break;
      }
    default:
      jj_la1[24] = jj_gen;
      ;
    }
}

  final public void elemento() throws ParseException {Token id; Token t;
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case IDENTIFICADOR:{
      id = jj_consume_token(IDENTIFICADOR);
Semantico.E1(id.image);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case ABRE_COLCHETES:{
        jj_consume_token(ABRE_COLCHETES);
        expressao();
Semantico.E2_Indice();
        jj_consume_token(FECHA_COLCHETES);
        break;
        }
      default:
        jj_la1[25] = jj_gen;
        ;
      }
Semantico.E_Generate();
      break;
      }
    case CONSTANTE_INTEIRA:{
      t = jj_consume_token(CONSTANTE_INTEIRA);
Semantico.C1(Integer.parseInt(t.image));
      break;
      }
    case CONSTANTE_REAL:{
      t = jj_consume_token(CONSTANTE_REAL);
Semantico.C2(Double.parseDouble(t.image));
      break;
      }
    case CONSTANTE_LITERAL:{
      t = jj_consume_token(CONSTANTE_LITERAL);
Semantico.C3(t.image);
      break;
      }
    case TRUE:{
      jj_consume_token(TRUE);
Semantico.C4();
      break;
      }
    case FALSE:{
      jj_consume_token(FALSE);
Semantico.C5();
      break;
      }
    case ABRE_PARENTESES:{
      jj_consume_token(ABRE_PARENTESES);
      expressao();
      jj_consume_token(FECHA_PARENTESES);
      break;
      }
    case NAO:{
      jj_consume_token(NAO);
      jj_consume_token(ABRE_PARENTESES);
      expressao();
      jj_consume_token(FECHA_PARENTESES);
Semantico.NOT();
      break;
      }
    default:
      jj_la1[26] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
}

// RECUPERAÇÃO DE ERROS
  final public 
void skipUntil(int[] syncTokens) throws ParseException {Token t;
while (true) {
      t = getToken(1);
      if (t == null || t.kind == 0) {if ("" != null) return;}
      boolean ok = false;
      for (int i=0; i<syncTokens.length; i++) {
        if (t.kind == syncTokens[i]) { ok = true; break; }
      }
      if (ok) {if ("" != null) return;}
      getNextToken();
    }
}

  /** Generated Token Manager. */
  public Linguagem20252TokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[27];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static {
	   jj_la1_init_0();
	   jj_la1_init_1();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0x0,0x4,0x0,0x800000,0x1e0,0x4000000,0x80000,0x80000,0x800000,0x18000,0x21e00,0x21e00,0x4000000,0x4000000,0x800000,0x4000000,0x0,0x4000,0x0,0x0,0xc0000000,0xc0000000,0x0,0x0,0x0,0x4000000,0x1018000,};
	}
	private static void jj_la1_init_1() {
	   jj_la1_1 = new int[] {0x4000,0x0,0x4000,0x0,0x0,0x0,0x0,0x0,0x0,0x38000,0x0,0x0,0x0,0x0,0x0,0x0,0x3c000,0x0,0x7e0,0x7e0,0x1000,0x1000,0x81b,0x81b,0x4,0x0,0x3e000,};
	}

  /** Constructor with InputStream. */
  public Linguagem20252(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Linguagem20252(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new Linguagem20252TokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 27; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 27; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public Linguagem20252(java.io.Reader stream) {
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new Linguagem20252TokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 27; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new Linguagem20252TokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 27; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public Linguagem20252(Linguagem20252TokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 27; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(Linguagem20252TokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 27; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[63];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 27; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		   if ((jj_la1_1[i] & (1<<j)) != 0) {
			 la1tokens[32+j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 63; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  private boolean trace_enabled;

/** Trace enabled. */
  final public boolean trace_enabled() {
	 return trace_enabled;
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

}
